### ISSUE TITLE
Project naming conflict.

### ISSUE THREAD

**Issue by amcgregor** [Sarvitech/WebCrux#1]
Howdy!

Just wanted to give you a heads up that your Symphony web framework application project appears to conflict with the name of my own FOSS ground-up web nanoframework, [WebCore](https://github.com/marrow/WebCore), a name that has been in use since 2006 or so.

Similarly, I am the owner and registrant of web-core.org and webcore.io, and my framework is the third link in a global Duckduckgo search for the name.  I would greatly appreciate if the name conflict could be resolved, especially as there is an overlap in problem domain between the projects.

Thanks!  :)

**Comment by SaeedPrez** [comment]
Hi @amcgregor,

This is supposed to be a private repository and only be used in our own projects and for our clients. The name doesn't matter and the only reason this package is public is so we can easily require it via composer. Also this repository is a small piece in a much bigger puzzle and is pretty useless to anyone without everything else.

With that said, if you still want me to change the name, let me know.

**Comment by amcgregor** [comment]
I had a look through the codebase, and there does seem to be enough similarity in component terms (routing, etc.) that there would still be a conflict in potential searches. Unfortunately I do have to request the change.  I can highly recommend use of organization or project namespaces, such as my other project's use of `marrow.` prefixes (such as `marrow.mailer`), WebCore is one of two exceptions to my own namespacing rule.  I've felt this pain myself, too; Marrow was formerly called Pulp (as a play on a competitor, Paste), which conflicted, and was changed when requested by the original mark holder.

Thank you very much for your understanding.

**Comment by SaeedPrez** [comment]
You've used the name for many years and it is important to you, I respect that and I'm glad to help. 

The repository is renamed now.

**Comment by amcgregor** [comment]
Thank you very, very much. I do greatly appreciate it. ❤️
